<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Dispatch - CENTRAL, in gs_platform.
 *
 * Everything here is generated by a MOBILE device and consumed by the Gemini
 * Console: a guard scanning a checkpoint, a guard failing an alertness
 * challenge, a resident pressing panic. The web screens that display it carry
 * a source badge, and until the mobile apps exist the simulator drives these
 * tables through the same endpoints the apps will use.
 *
 * Central because dispatch is a cross-client operation: one dispatcher watches
 * every estate at once, and a per-estate table would make that a fan-out.
 *
 * NOTE on biometrics and location (invariants 9 and 12):
 *   - alertness_checks stores a derived SCORE and an event time. No image, no
 *     template, no raw sensor data. There is no image anywhere in this system.
 *   - Locations are coarse and optional. Refusing a permission degrades
 *     accuracy and says so; it never removes panic or clock-in.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('duress_alerts', function (Blueprint $table) {
            $table->id();
            $table->string('tenant_id');

            // panic | duress | medical | fire | intrusion
            $table->string('kind', 32);

            // Who raised it. Exactly one of these is set.
            $table->foreignId('guard_id')->nullable()->constrained('guards')->nullOnDelete();
            $table->string('raised_by_name', 160)->nullable();  // resident, denormalised
            $table->string('unit_reference', 32)->nullable();

            // open | acknowledged | responding | resolved | false_alarm
            $table->string('status', 24)->default('open');

            $table->decimal('latitude', 10, 7)->nullable();
            $table->decimal('longitude', 10, 7)->nullable();

            /*
             * Device time alongside server time, never silently reconciled.
             * A device with a wrong clock is a fact worth keeping, and a
             * rewritten timestamp destroys the evidence that it happened.
             */
            $table->timestamp('device_time')->nullable();
            $table->timestamp('server_time')->useCurrent();
            $table->boolean('clock_skewed')->default(false);
            $table->boolean('captured_offline')->default(false);

            /*
             * Client-generated idempotency key. An offline device retries on
             * reconnect, and a panic alert must never be duplicated by a retry.
             */
            $table->string('idempotency_key', 64)->nullable()->unique();

            $table->foreignId('acknowledged_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('acknowledged_at')->nullable();
            $table->timestamp('resolved_at')->nullable();
            $table->text('resolution_note')->nullable();

            // Marks a row created by the simulator rather than a real device,
            // so the source badge can say so honestly.
            $table->boolean('is_simulated')->default(false);

            $table->timestamps();

            $table->index(['status', 'server_time']);
            $table->index(['tenant_id', 'status']);
        });

        Schema::create('patrol_checkpoints', function (Blueprint $table) {
            $table->id();
            $table->string('tenant_id');
            $table->foreignId('post_id')->nullable()->constrained('posts')->nullOnDelete();
            $table->string('label', 120);
            $table->string('code', 64)->unique();
            $table->unsignedSmallInteger('sequence')->default(0);
            $table->boolean('is_active')->default(true);
            $table->timestamps();

            $table->index(['tenant_id', 'sequence']);
        });

        Schema::create('checkpoint_scans', function (Blueprint $table) {
            $table->id();
            $table->foreignId('patrol_checkpoint_id')->constrained()->cascadeOnDelete();
            $table->foreignId('guard_id')->constrained('guards')->cascadeOnDelete();

            $table->timestamp('device_time')->nullable();
            $table->timestamp('server_time')->useCurrent();
            $table->boolean('clock_skewed')->default(false);
            $table->boolean('captured_offline')->default(false);
            $table->string('idempotency_key', 64)->nullable()->unique();
            $table->boolean('is_simulated')->default(false);

            $table->index(['guard_id', 'server_time']);
        });

        Schema::create('alertness_checks', function (Blueprint $table) {
            $table->id();
            $table->foreignId('guard_id')->constrained('guards')->cascadeOnDelete();

            /*
             * A DERIVED SCORE and an event time. Nothing else.
             *
             * Invariant 9: biometrics never leave the device. No template, no
             * landmark set, no image. This column could not reconstruct a face
             * if someone tried.
             */
            $table->unsignedTinyInteger('score')->nullable();

            // passed | missed | failed | declined
            // `declined` is a first-class outcome: refusing the check degrades
            // monitoring and is recorded as such, and never blocks duty.
            $table->string('outcome', 24);

            $table->timestamp('device_time')->nullable();
            $table->timestamp('server_time')->useCurrent();
            $table->boolean('is_simulated')->default(false);

            $table->index(['guard_id', 'server_time']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('alertness_checks');
        Schema::dropIfExists('checkpoint_scans');
        Schema::dropIfExists('patrol_checkpoints');
        Schema::dropIfExists('duress_alerts');
    }
};
